
name: Build and test go-ms-runtime
on:
  push:
    branches:
      - 'release-**'

jobs:

  build:
    name: Build and test go-ms-runtime
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out this code
        uses: actions/checkout@v2
        with:
          path: 'go-ms'

      - name: Check out go-ms-runtime
        uses: actions/checkout@v2
        with:
          repository: 'yadisnel/go-ms-runtime'
          path: 'go-ms-runtime'

      - name: Build all
        run: $GITHUB_WORKSPACE/go-ms/.github/workflows/scripts/build-go-ms-runtime.sh $GITHUB_SHA
        working-directory: go-ms-runtime